bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users


  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  attachment :profile_image

  validates :name, length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

        <% if @user.errors.any? %>
          <div class= "text-danger">
            <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class= "form-group">
          <label for="inputName">Name</label><br />
          <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control" %>
        </div>
        <div class= "form-group">
          <label for="inputImage">Image</label><br />
          <%= f.attachment_field :profile_image  %>
        </div>
        <div class= "form-group">
          <label for="inputIntroduction">Introduction</label><br />
          <%= f.text_area :introduction, id:"inputIntroduction", class: "form-control" %>
        </div>
        <div class= "form-group">
          <%= f.submit "Update User",class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<p id="notice"></p>
<div class= "container px-5 px-sm-0">
  <div class= "row">
    <div class= "col-md-3">
      <%= render 'books/userinfo', book: Book.new, user: @user %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class= "table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数: <%= user.followings.count %></td>
              <td>フォロワー数: <%= user.followings.count %></td>
              <td>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                   <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user)  %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
<p class="notice text-success" >
  <%= flash[:notice] %>
</p>
<div class= "container px-5 px-sm-0">
  <div class= "row">
    <div class= "col-md-3">
      <%= render 'books/userinfo', book: Book.new, user: @user %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class= "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>Rate</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                <div id="star-rate-<%= book.id %>"></div>
                <script>
                  $("#star-rate-<%= book.id %>").raty({
                  size: 36,
                  starOn: "/assets/star-on.png",
                  starOff: "/assets/star-off.png",
                  readOnly: true,
                  score: <%= book.rate %>,
                  });
                </script>
              </td>
              <td><%= link_to "コメント数: #{book.post_comments.count}", book_path(book.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>