bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users


  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookers2/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.book_id = @book.id
    @post_comment.user_id = current_user.id
    if @post_comment.save
      render 'create'
    else
      @user = current_user
      render 'books/show'
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @post_comment = @book.post_comments.find(params[:id])
    @post_comment.destroy
  end



  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

bookers2/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2/app/views/post_comments/_comment.html.erb
<% book.post_comments.each do |post_comment| %>
  <%= link_to user_path(post_comment.user) do %>
    <%= attachment_image_tag post_comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
  <% end %>
  <%= post_comment.comment %>
  <% if post_comment.user == current_user %>
    <%= link_to 'Destroy',book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true,"data-confirm" => "本当に消しますか？",class:'btn btn-sm btn-danger' %>
  <% end %><br>
  <%= link_to post_comment.user.name, user_path(post_comment.user) %><br>
<% end %>

<%= form_with(model:[@book,@post_comment]) do |f| %>
  <%= f.text_area :comment, class: "form-control" %><br>
  <%= f.submit "送信" %>
<% end %>

bookers2/app/views/post_comments/create.js.erb
$("#comments_area").html("<%= j(render 'post_comments/comment', book: @book) %>");

$("textarea").val('');

bookers2/app/views/post_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'post_comments/comment', book: @book) %>");

$("textarea").val('');