bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users


  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :categorymaps, dependent: :destroy
  has_many :categories, through: :categorymaps

  def save_category(sent_categories)
    current_categories = self.categories.pluck(:category_name) unless self.categories.nil?
    old_categories = current_categories - sent_categories
    new_categories = sent_categories - current_categories

    old_categories.each do |old|
      self.categories.delete Category.find_by(category_name: old)
    end

    new_categories.each do |new|
      new_book_category = Category.find_or_create_by(category_name: new)
      self.categories << new_book_category
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  validates :rate,numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

bookers2/app/models/category.rb
class Category < ApplicationRecord
  has_many :categorymaps, dependent: :destroy
  has_many :books, through: :categorymaps
end

bookers2/app/models/categorymap.rb
class Categorymap < ApplicationRecord
  belongs_to :book
  belongs_to :category
  
  validates :book_id, presence: true
  validates :category_id, presence: true
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  attachment :profile_image

  validates :name, length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    category_list = params[:book][:category_name].delete(' ').delete('　').split(',')
    if @book.save
      @book.save_category(category_list)
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    if params[:sort] == "rate"
      @books = Book.order(rate: "DESC")
    elsif params[:sort] == "updated_at"
      @books = Book.order(updated_at: "DESC")
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_categories = @book.categories
    @user = @book.user
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if  current_user != @book.user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id, :rate)
  end

  def sort_params
    params.permit(:sort)
  end



end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @method = params["method"]
    @content = params["content"]
    @records = search_for(@model,@method,@content)
  end

  private
  def search_for(model,method,content)
    if model == 'user'
      if method == 'perfect'
        User.where(name:content)
      elsif method == 'prefix'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end

    elsif model == 'book'
      if method == 'perfect'
        Book.where(title:content)
      elsif method == 'prefix'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end

    elsif model == 'category'
      if method == 'perfect'
        Category.where(category_name:content)
      elsif method == 'prefix'
        Category.where('category_name LIKE ?', content+'%')
      elsif method == 'backward'
        Category.where('category_name LIKE ?', '%'+content)
      else
        Category.where('category_name LIKE ?', '%'+content+'%')
      end
    end
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class= "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class= "container">
          <a class= "navbar-brand" href= "/">
            <span>Bookers</span>
          </a>
            <button class= "navbar-toggler" type= "button" data-toggle= "collapse" data-target= "#navbarNavDropdown" aria-controls= "navbarNavDropdown" aria-expanded= "false" aria-label= "Toggle navigation">
            <span class= "navbar-toggler-icon"></span>
          </button>
          <div class= "navbar-collapse collapse" id="navbarNavDropdown" style>
            <ul class= "navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li>
                <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li>
                <%= link_to " Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
              </li>
              <% else %>
              <li>
                <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to " About", home_about_path,class: 'fas fa-link nav-link text-light' %>
              </li>
              <li>
                <%= link_to " Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
              </li>
              <li>
                <%= link_to " Log in", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if user_signed_in? %>
        <%= form_with url:search_path, method: :get, local:true do |f| %>
        <div class="col text-center mt-2">
          <%= f.text_field 'content' %>
          <%= f.select 'model', options_for_select({"User" => "user", "Book" => "book", "Category" => "category"}) %>
          <%= f.select 'method', options_for_select({"完全一致" => "perfect", "前方一致" => "prefix", "後方一致" => "bac", "部分一致" => "partical"}) %>
          <%= f.submit '検索' %>
        </div>
        <% end %>
      <% end %>
    </header>

    <%= yield %>
  </body>

  <footer>
    <div class = "container mt-5">
      <dic class = "row">
        <div class = "mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </dic>
    </div>
  </footer>


</html>