bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users


  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :categorymaps, dependent: :destroy
  has_many :categories, through: :categorymaps

  def save_category(sent_categories)
    current_categories = self.categories.pluck(:category_name) unless self.categories.nil?
    old_categories = current_categories - sent_categories
    new_categories = sent_categories - current_categories

    old_categories.each do |old|
      self.categories.delete Category.find_by(category_name: old)
    end

    new_categories.each do |new|
      new_book_category = Category.find_or_create_by(category_name: new)
      self.categories << new_book_category
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  validates :rate,numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    category_list = params[:book][:category_name].delete(' ').delete('　').split(',')
    if @book.save
      @book.save_category(category_list)
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    if params[:sort] == "rate"
      @books = Book.order(rate: "DESC")
    elsif params[:sort] == "updated_at"
      @books = Book.order(updated_at: "DESC")
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_categories = @book.categories
    @user = @book.user
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if  current_user != @book.user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id, :rate)
  end

  def sort_params
    params.permit(:sort)
  end



end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_sort.html.erb
<%= link_to '新しい順', :sort => "updated_at" %>
|
<%= link_to '評価の高い順', :sort => "rate" %>

bookers2/app/views/books/_userinfo.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class= "table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
       <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to "#{user.followings.count}", user_followings_path(user.id) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to "#{user.followers.count}", user_followers_path(user.id) %></th>
    </tr>
  </tbody>
</table>

<div class= "row">
  <% if @user == current_user %>
    <%= link_to "", edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
    <% end %>
  <% end %>
</div>



<h2 class= "mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <%= f.label "title","Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "opinion","Opinion" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "category","Category" %>
    <%= f.text_field :category_name, value: @category_list, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "rate","Rate" %>
    <div id="star"></div>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

<script>
  $("#star").raty({
    size: 36,
    starOn: "/assets/star-on.png",
    starOff: "/assets/star-off.png",
    scoreName: 'book[rate]'
  });
</script>

bookers2/app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

        <% if @book.errors.any? %>
          <div class= "text-danger">
            <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <%= form_with model:@book, local:true do |f| %>
        <div class= "form-group">
          <label for="book_title">Title</label><br />
          <%= f.text_field :title, autofocus: true, id:"book_title", class: "form-control" %>
        </div>
        <div class= "form-group">
          <label for="book_opinion">Opinion</label><br />
          <%= f.text_area :body, id:"book_opinion", class: "form-control" %>
        </div>
        <div id="star-rate-<%= @book.id %>"></div>
          <script>
            $("#star-rate-<%= @book.id %>").raty({
            size: 36,
            starOn: "/assets/star-on.png",
            starOff: "/assets/star-off.png",
            readOnly: true,
            score: <%= @book.rate %>,
            });
          </script>
        <div class= "form-group">
          <%= f.submit "Update Book",class: "btn btn-success mt-3" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path  %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<p id="notice"></p>
<div class= "container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <div class= "text-danger">
      <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "row">
    <div class= "col-md-3">
      <%= render 'books/userinfo', book: @book, user: @user %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <div id= "sort"><%= render 'books/sort' %></div>
        <table class= "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>Category</th>
              <th>Rate</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                <% book.categories.each do |category| %>
                  <%= category.category_name %>
                <% end %>
              </td>
              <td>
                <div id="star-rate-<%= book.id %>"></div>
                <script>
                  $("#star-rate-<%= book.id %>").raty({
                  size: 36,
                  starOn: "/assets/star-on.png",
                  starOff: "/assets/star-off.png",
                  readOnly: true,
                  score: <%= book.rate %>,
                  });
                </script>
              </td>
              <td id="favorite-btn_<%= book.id %>">
                <%= render 'favorites/favorite-btn',book: book %>
              </td>
              <td>
                <%= link_to "コメント数: #{book.post_comments.count}", book_path(book.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<p class="notice text-success" >
  <%= flash[:notice] %>
</p>
<div class= "container px-5 px-sm-0">
  <div class= "row">
    <div class= "col-md-3">
      <%= render 'books/userinfo', book: Book.new, user: @book.user %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class= "table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
                <% end %>
                <%= link_to @book.user.name, user_path(@book.user) %>
              </td>
              <td><%= link_to @book.title, book_path(@book) %></td>
              <td><%= @book.body %></td>
              <td>
                <% @book_categories.each do |category| %>
                  <%= category.category_name %>
                <% end %>
              </td>
              <td>
                <div id="star-rate-<%= @book.id %>"></div>
              </td>
              <td id="favorite-btn_<%= @book.id %>">
                <%= render 'favorites/favorite-btn',book: @book %>
              </td>
              <td>コメント数: <%= @book.post_comments.count %></td>
              <% if @user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to 'Destroy',book_path(@book), method: :delete,"data-confirm" => "本当に消しますか？",class:'btn btn-sm btn-danger' %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <div id="comments_area">
          <%= render 'post_comments/comment',book: @book %>
        </div>
    </div>
  </div>
</div>

<script>
  $("#star-rate-<%= @book.id %>").raty({
    size: 36,
    starOn: "/assets/star-on.png",
    starOff: "/assets/star-off.png",
    readOnly: true,
    score: <%= @book.rate %>,
  });
</script>